### ISSUE TITLE
$templatePath removed in Slim 2.3.0

### ISSUE THREAD

**Issue by matthkunze** [petebrowne/slim-layout-view#1]
In Slim 2.3.0 the protected property $templatePath in Slim/View.php was removed. That produces an application error like this:

```
Undefined property: Slim\LayoutView::$templatesPath
```

To avoid this, change $this->templatePath in LayoutView.php to $this->templateDirectory (Lines 65 and 68). The fixed method renderLayout:

```
protected function renderLayout($layout, $yield) {
    $currentTemplate = $this->templatesDirectory;
    $this->setData('yield', $yield);
    $result = $this->render($layout);
    $this->templatesDirectory = $currentTemplate;
    $this->unsetData('yield');

    return $result;
}
```

**Comment by petebrowne** [comment]
Thanks, can you make a pull request? I'll just merge it in

**Comment by nickelfault** [comment]
I'm using Slim 2.3.1 (fresh project), and am getting the following exception:

Type: ErrorException
Code: 8
Message: Undefined property: Slim\LayoutView::$templateDirectory
File: C:\inetpub\wwwroot\auth-slim\Slim\LayoutView.php
Line: 65

I'm assuming this may be related to this issue, any ideas?

**Comment by tuupola** [comment]
Above patch does not work with 2.3.1.

**Comment by nickelfault** [comment]
Tried 2.3.0 and am getting the same error as well.

**Comment by petebrowne** [comment]
See: [0.2.1](https://github.com/petebrowne/slim-layout-view/tree/v0.2.1)

**Comment by julionc** [comment]
@petebrowne thx. Update the README - installation section.

```
"petebrowne/slim-layout-view": "0.2.*"
```

**Comment by petebrowne** [comment]
Updated the README as well, thanks
